### ISSUE TITLE
setenv-prod and setenv-dev commands out of switch cmd

### ISSUE THREAD

**Issue by MikeOverbeck** [Inventsable/bombino-commands#14]
The switch command is great for toggling between production and development modes.
But I'd like to be able to do a force switch regardless of my current manifest status.
This could be used as a pre-build step in my package.json to ensure that the manifest is set correctly before building and signing.
Exposing the `getCurrentContext` function would be a good start. I'd be happy to attempt a PR.

**Comment by Inventsable** [comment]
Hey Mike, I'm actually a planning for a full rewrite of certain things, like merging `bombino` and `bombino-commands` together with a `bombino.config.js` file similar to how frameworks and libraries like Vue and Quasar structure their own with a lot more interactivity. At Battleaxe, Adam made a similar request to this via `npm run package`, which forces switch to prod, builds, signs and certifies a ZXP, then produces a ZIP as a folder containing other files like install instructions bundled with the ZXP, then finally switching back to dev context (if this was ran from dev context) in the panel and notifying the user. The check to see if the context is set correctly before signing is a good point, since I've accidentally signed the wrong context more than once myself.

A lot of the code here is sloppy and was mostly written 2+ years ago before I grasped certain concepts. I can do this fairly easily for you or even PR the `package` command, but know that it's not my ideal solution and I'm opting for a rewrite fairly soon. I won't get to this for a few days, though.

**Comment by MikeOverbeck** [comment]
Wow, you type fast!!
Good to know this is on your radar. There is no need for a PR as I can build my own workarounds for now. Go full-steam on that rewrite!
