### ISSUE TITLE
'ZXPSignCmd' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by gersirami** [Inventsable/bombino-commands#15]
Hello Tom!
You have set up such great tools.

I'm trying create a **.zxp** and after using `npm run sign` but I keep getting nothing.
A bunch of messages following: `'ZXPSignCmd' is not recognized as an internal or external command,
operable program or batch file.`
Em I missing something?

Best regards!

**Comment by Inventsable** [comment]
Hello and thanks!

The way this command works may be a bit obtuse. Essentially it immediately runs a `cd ../` command to visit the parent, then tries to run ZXPSignCmd, creates a temporary clone of the current panel, bundles it, then deletes the clone and places the ZXP in the original panel's `./.archive` folder.

[You'll need to download the latest version of ZXPSignCommand for your OS](https://github.com/Adobe-CEP/CEP-Resources/tree/master/ZXPSignCMD). Then the `ZXPSignCmd.exe` file from there must be included as a sibling to your original panel, for example if your panel is:

`.../AppData/Roaming/cep/extensions/myPanel`

Then you'd need it to be located at:

`.../AppData/Roaming/cep/extensions/ZXPSignCmd.exe`

The reason for this is because I couldn't find a pure node solution that worked for all users and I didn't feel comfortable bundling ZXPSignCmd with every single template, which would include a lot of validation logic to determine which version and OS to use, etc.

Let me know if you're still having issues despite the above.

**Comment by gersirami** [comment]
🤦‍♂️My bad. Now I see you **flagged** that in the README. **Worked perfectly now!**
I'm a visual learner, but for this I'll have to read all the docs, appears it's the only source of guidance for Adobe CEP & VueJS.
Any recommendations on where to start?!

**Comment by Inventsable** [comment]
No worries. To be honest, CEP isn't that complicated, it's mostly the same as doing anything with HTML/CSS/JS but requires a few additional files and a bit of setup (which is what bombino attempts to take care of for you). Most of us in this space are artists turned programmers and rarely the other way around, so we're often all visual learners including myself.

If I were to go back and do things over, I'd focus more on general web dev and less on Adobe specific things. You don't need a scripting tutorial (which there aren't many of) to learn how to script -- you need a Javascript tutorial (which there's ton of) and then to apply what you've learned there to the context of scripting, just be careful not to get too modern because scripting is a subset of ECMA Edition 3 and doesn't support things like let/const, arrow functions, new prototype methods for arrays and etc like filter/reduce (though there are shims for this to allow it to run like my own [gehenna](https://github.com/battleaxedotco/gehenna) package). Similarly it's not too necessary to find CEP specific tutorials, it'd be more relevant to find VueJS 2 tutorials and apply what you've learned there to a bombino template, or Vue 3 to a [BOLT-CEP](https://github.com/hyperbrew/bolt-cep) template since my own bombei package for Vue 3 is still in the works and not ready just yet. I'd recommend some cheap Udemy video classes on VueJS pre-Vue 3 which is the newest version not supported in these templates, and basic Javascript classes preferably not focused on ES6/2018+ syntax though [I also have utilities for converting a lot of code from these down to what's supported in scripting](https://github.com/Inventsable/scriptonium), along with the [aeenhancers](https://ai-scripting.docsforadobe.dev/) guide to the particular app you're using. I have many links for references like this in my [Ovid web editor](https://ovid-editor.web.app/).

**Comment by gersirami** [comment]
Well, I do have some javascript knowledge.
Followed some cheap courses like you suggested and completed freecodecamp lessons about JS.
I have built some scripts and extensions to avoid some mechanical tasks I had to do at my job, but using only vanilla javascript it's a loss of time I think, although it's the best way to learn the basics. I really like Vue JS and find it the most intuitive framework in the trio of Vue/React/Angular.

As much as I like coding I do it only in my free time, but I will be going through your tools, which are all awesome by the way, also a little too advanced for me right now, since I still have to figure out some things like VueX 😅.

PS: I played a little with the Ovid editor in After Effects, great tool.

Thank you very much Tom for everything you and your contributors have built.
